import { TransactionItem } from "../_pages/types";

export const INITIAL_TRANSACTIONS: TransactionItem[] = [
  {
    id: "TRX100234",
    userId: "USR001",
    userName: "Alice Smith",
    userEmail: "alice@example.com",
    userAvatar: "https://api.dicebear.com/7.x/identicon/svg?seed=AliceSmith",
    planName: "Premium Yearly",
    amount: 199.99,
    currency: "USD",
    status: "SUCCESS",
    paymentMethod: "Credit Card (Visa ending in 4242)",
    transactionDate: "2023-11-20T10:30:00Z",
    description: "Yearly premium subscription renewal",
  },
  {
    id: "TRX100235",
    userId: "USR002",
    userName: "Bob Johnson",
    userEmail: "bob.j@example.com",
    userAvatar: "https://api.dicebear.com/7.x/identicon/svg?seed=BobJohnson",
    planName: "Basic Monthly",
    amount: 9.99,
    currency: "USD",
    status: "PENDING",
    paymentMethod: "PayPal",
    transactionDate: "2023-11-22T14:15:00Z",
    description: "Monthly basic subscription",
  },
  {
    id: "TRX100236",
    userId: "USR003",
    userName: "Charlie Davis",
    userEmail: "charlie@example.com",
    userAvatar: "https://api.dicebear.com/7.x/identicon/svg?seed=CharlieDavis",
    planName: "Enterprise Plan",
    amount: 499.00,
    currency: "USD",
    status: "FAILED",
    paymentMethod: "Bank Transfer",
    transactionDate: "2023-11-23T09:00:00Z",
    description: "Insufficient funds",
  },
  {
    id: "TRX100237",
    userId: "USR004",
    userName: "Diana Prince",
    userEmail: "diana@example.com",
    userAvatar: "https://api.dicebear.com/7.x/identicon/svg?seed=DianaPrince",
    planName: "Premium Monthly",
    amount: 19.99,
    currency: "USD",
    status: "SUCCESS",
    paymentMethod: "Apple Pay",
    transactionDate: "2023-11-24T16:45:00Z",
    description: "Monthly premium subscription",
  },
];
