import { UserItem } from "../_pages/types";

export const INITIAL_USERS: UserItem[] = [
    {
        id: "USR001",
        name: "Alex Mercer",
        email: "alex.mercer@vifc.io",
        role: "ADMIN",
        status: "ACTIVE",
        phone: "+1 (555) 019-2834",
        joinedDate: "2026-01-15",
        lastActive: "Just now",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Alex",
    },
    {
        id: "USR002",
        name: "Sophia Vance",
        email: "sophia.vance@vifc.io",
        role: "SHOP",
        status: "ACTIVE",
        phone: "+1 (555) 024-8192",
        joinedDate: "2026-02-10",
        lastActive: "5 mins ago",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Sophia",
    },
    {
        id: "USR003",
        name: "Ethan Carter",
        email: "ethan.carter@gmail.com",
        role: "BUYER",
        status: "ACTIVE",
        phone: "+1 (555) 091-2384",
        joinedDate: "2026-03-01",
        lastActive: "2 hours ago",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Ethan",
    },
    {
        id: "USR004",
        name: "Olivia Sterling",
        email: "olivia.sterling@biz.com",
        role: "BUSINESS",
        status: "INACTIVE",
        phone: "+1 (555) 072-4912",
        joinedDate: "2026-04-12",
        lastActive: "3 days ago",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Olivia",
    },
    {
        id: "USR005",
        name: "Marcus Brody",
        email: "marcus.brody@vifc.io",
        role: "EMPLOYEE",
        status: "ACTIVE",
        phone: "+1 (555) 083-2941",
        joinedDate: "2026-02-28",
        lastActive: "1 day ago",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Marcus",
    },
    {
        id: "USR006",
        name: "Luna Everly",
        email: "luna.everly@logistics.com",
        role: "LOGISTICS",
        status: "BANNED",
        phone: "+1 (555) 042-9182",
        joinedDate: "2026-01-20",
        lastActive: "1 week ago",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Luna",
    },
    {
        id: "USR007",
        name: "Daniel Drake",
        email: "daniel.drake@sales.com",
        role: "SALE",
        status: "ACTIVE",
        phone: "+1 (555) 063-2918",
        joinedDate: "2026-05-05",
        lastActive: "10 mins ago",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Daniel",
    },
    {
        id: "USR008",
        name: "Zoe Thorne",
        email: "zoe.thorne@gmail.com",
        role: "BUYER",
        status: "ACTIVE",
        phone: "+1 (555) 039-2810",
        joinedDate: "2026-05-18",
        lastActive: "Just now",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Zoe",
    },
    {
        id: "USR009",
        name: "Aiden Vance",
        email: "aiden.vance@biz.com",
        role: "BUSINESS",
        status: "ACTIVE",
        phone: "+1 (555) 011-2834",
        joinedDate: "2026-05-01",
        lastActive: "4 mins ago",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Aiden",
    },
    {
        id: "USR010",
        name: "Chloe Westwood",
        email: "chloe.westwood@shop.io",
        role: "SHOP",
        status: "ACTIVE",
        phone: "+1 (555) 099-2812",
        joinedDate: "2026-05-10",
        lastActive: "1 hour ago",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Chloe",
    },
    {
        id: "USR011",
        name: "Gabriel Stone",
        email: "gabriel.stone@vifc.io",
        role: "ADMIN",
        status: "ACTIVE",
        phone: "+1 (555) 021-9843",
        joinedDate: "2026-04-20",
        lastActive: "12 mins ago",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Gabriel",
    },
    {
        id: "USR012",
        name: "Seraphina Frost",
        email: "seraphina.frost@vifc.io",
        role: "EMPLOYEE",
        status: "ACTIVE",
        phone: "+1 (555) 088-2931",
        joinedDate: "2026-03-15",
        lastActive: "4 hours ago",
        avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Seraphina",
    },
];