import { NewsItem } from "../_pages/types";

export const INITIAL_NEWS: NewsItem[] = [
  {
    id: "NEWS001",
    title: "Web3 Commerce – The New Shopping Trend of the Future",
    slug: "web3-commerce-the-new-shopping-trend-of-the-future",
    summary: "Web3 Commerce is changing the way we shop and own digital assets. A comprehensive analysis of this trend.",
    content: "Web3 Commerce (decentralized e-commerce) is a new shopping model based on blockchain technology, allowing users to truly own digital assets and pay without intermediaries.",
    category: ["Web3"],
    tags: ["Web3", "Commerce", "Blockchain"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=web3",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PUBLISHED",
    createdDate: "25/05/2024 10:30",
    views: 2548,
    seoTitle: "Web3 Commerce – The New Shopping Trend of the Future",
    seoDescription: "Web3 Commerce is changing the way we shop and own digital assets. Learn more details here.",
    seoKeywords: "web3, commerce, blockchain, vifc",
    allowComments: true,
    isFeatured: true,
    scheduledDate: "",
  },
  {
    id: "NEWS002",
    title: "Bitcoin Surpasses $70,000 – What is Happening?",
    slug: "bitcoin-surpasses-70000-what-is-happening",
    summary: "Bitcoin has officially crossed the $70,000 mark again. Analyzing macro factors and ETF inflows.",
    content: "Bitcoin prices surged past $70,000 driven by continuous inflows into spot Bitcoin ETFs and the upcoming Halving event.",
    category: ["Crypto"],
    tags: ["Bitcoin", "Crypto", "Halving"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=bitcoin",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PUBLISHED",
    createdDate: "24/05/2024 15:45",
    views: 1875,
    seoTitle: "Bitcoin Surpasses $70,000 – Latest Crypto Market Update",
    seoDescription: "Bitcoin reaches $70k. Learn about the macro factors and the next trends.",
    seoKeywords: "bitcoin, crypto, 70k, halving",
    allowComments: true,
    isFeatured: false,
    scheduledDate: "",
  },
  {
    id: "NEWS003",
    title: "Top 10 NFT Collections to Watch in May 2024",
    slug: "top-10-nft-collections-to-watch-in-may-2024",
    summary: "May witnessed the explosion of many impressive NFT collections on Layer 2 ecosystems.",
    content: "Next-generation NFT collections are focusing on utility (Utility NFTs) rather than just being digital artwork.",
    category: ["NFT"],
    tags: ["NFT", "DigitalArt", "Layer2"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=nft",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PUBLISHED",
    createdDate: "23/05/2024 09:15",
    views: 1234,
    seoTitle: "Top 10 NFT Collections to Watch in May 2024",
    seoDescription: "Summary of potential NFTs and NFT market trends.",
    seoKeywords: "nft, collections, digital art",
    allowComments: false,
    isFeatured: false,
    scheduledDate: "",
  },
  {
    id: "NEWS004",
    title: "What is the Metaverse? The Future of the Internet",
    slug: "what-is-the-metaverse-the-future-of-the-internet",
    summary: "Metaverse is not just a passing trend, but could be the future of the next generation of the Internet.",
    content: "The virtual world Metaverse integrating VR/AR will create a completely new workspace, playground, and commerce beyond physical limits.",
    category: ["Metaverse"],
    tags: ["Metaverse", "VR", "AR"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=metaverse",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "DRAFT",
    createdDate: "22/05/2024 14:20",
    views: 0,
    seoTitle: "What is the Metaverse? Future Tech Trends",
    seoDescription: "Learn the definition of the Metaverse and the development potential of the virtual universe.",
    seoKeywords: "metaverse, vr, ar, future",
    allowComments: true,
    isFeatured: false,
    scheduledDate: "",
  },
  {
    id: "NEWS005",
    title: "What is a Smart Contract? A Detailed Guide for Beginners",
    slug: "what-is-a-smart-contract-a-detailed-guide-for-beginners",
    summary: "Smart Contracts are the core foundation of Web3. Learn how they work and their practical applications.",
    content: "Smart contracts automatically execute terms when conditions are met without the need for a trusted third party.",
    category: ["Blockchain"],
    tags: ["SmartContract", "Solidity", "Blockchain"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=smartcontract",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PENDING_REVIEW",
    createdDate: "21/05/2024 11:05",
    views: 0,
    seoTitle: "What is a Smart Contract? Blockchain Guide for Beginners",
    seoDescription: "Easiest guide to blockchain smart contracts.",
    seoKeywords: "smart contract, solidity, blockchain, web3",
    allowComments: true,
    isFeatured: false,
    scheduledDate: "",
  },
  {
    id: "NEWS006",
    title: "What is DeFi? Opportunities and Risks in DeFi",
    slug: "what-is-defi-opportunities-and-risks-in-defi",
    summary: "DeFi is opening up a decentralized financial era. Let's explore yield opportunities and the risks involved.",
    content: "Decentralized finance (DeFi) allows borrowing, trading, and earning yield completely peer-to-peer through blockchain protocols.",
    category: ["DeFi"],
    tags: ["DeFi", "YieldFarming", "Lending"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=defi",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PUBLISHED",
    createdDate: "20/05/2024 08:30",
    views: 3421,
    seoTitle: "What is DeFi? Investment Opportunities and Risks",
    seoDescription: "Everything you need to know about decentralized finance (DeFi).",
    seoKeywords: "defi, yield farming, lending, crypto",
    allowComments: true,
    isFeatured: true,
    scheduledDate: "",
  },
  {
    id: "NEWS007",
    title: "Guide to Securing Your Crypto Wallet 100%",
    slug: "guide-to-securing-your-crypto-wallet-100",
    summary: "Crypto wallet security is paramount to protect your digital assets from hackers.",
    content: "Keep your recovery seed phrase completely offline, never take a picture to store on your phone, and use cold storage for large amounts.",
    category: ["Tutorial"],
    tags: ["Security", "Wallet", "Crypto"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=security",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PUBLISHED",
    createdDate: "19/05/2024 16:10",
    views: 2111,
    seoTitle: "Secure Crypto Wallet | Step-by-Step Guide 2024",
    seoDescription: "Vital principles to protect your crypto wallet.",
    seoKeywords: "wallet security, crypto wallet, seed phrase, cold storage",
    allowComments: true,
    isFeatured: false,
    scheduledDate: "",
  }
];

export const CATEGORY_OPTIONS = [
  { label: "Web3", value: "Web3" },
  { label: "Crypto", value: "Crypto" },
  { label: "NFT", value: "NFT" },
  { label: "Metaverse", value: "Metaverse" },
  { label: "Blockchain", value: "Blockchain" },
  { label: "DeFi", value: "DeFi" },
  { label: "Tutorial", value: "Tutorial" }
];

export const STATUS_OPTIONS = [
  { label: "All Statuses", value: "ALL" },
  { label: "Published", value: "PUBLISHED" },
  { label: "Draft", value: "DRAFT" },
  { label: "Pending Review", value: "PENDING_REVIEW" },
  { label: "Archived", value: "ARCHIVED" }
];
