import { NewsItem } from "../_pages/types";

export const INITIAL_NEWS: NewsItem[] = [
  {
    id: "NEWS001",
    title: "Web3 Commerce – Xu hướng mua sắm mới của tương lai",
    slug: "web3-commerce-xu-huong-mua-sam-moi-cua-tuong-lai",
    summary: "Web3 Commerce đang thay đổi cách chúng ta mua sắm và sở hữu tài sản số. Bài viết phân tích toàn diện về xu hướng này.",
    content: "Web3 Commerce (thương mại điện tử phi tập trung) là mô hình mua sắm mới dựa trên công nghệ blockchain, cho phép người dùng sở hữu thực sự các tài sản số và thanh toán không cần trung gian.",
    category: "Web3",
    tags: ["Web3", "Commerce", "Blockchain"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=web3",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PUBLISHED",
    createdDate: "25/05/2024 10:30",
    views: 2548,
    seoTitle: "Web3 Commerce – Xu hướng mua sắm mới của tương lai",
    seoDescription: "Web3 Commerce đang thay đổi cách chúng ta mua sắm và sở hữu tài sản số. Tìm hiểu chi tiết tại đây.",
    seoKeywords: "web3, commerce, blockchain, vifc",
    allowComments: true,
    isFeatured: true,
    scheduledDate: "",
  },
  {
    id: "NEWS002",
    title: "Bitcoin vượt $70,000 – Điều gì đang xảy ra?",
    slug: "bitcoin-vuot-70000-dieu-gi-dang-xay-ra",
    summary: "Bitcoin đã chính thức vượt mốc $70,000 một lần nữa. Cùng phân tích các yếu tố vĩ mô và dòng vốn ETF.",
    content: "Giá Bitcoin đã tăng mạnh vượt $70,000 nhờ dòng vốn liên tục chảy vào các quỹ ETF Bitcoin giao ngay cùng sự kiện Halving đang cận kề.",
    category: "Crypto",
    tags: ["Bitcoin", "Crypto", "Halving"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=bitcoin",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PUBLISHED",
    createdDate: "24/05/2024 15:45",
    views: 1875,
    seoTitle: "Bitcoin vượt $70,000 – Cập nhật thị trường Crypto mới nhất",
    seoDescription: "Bitcoin đạt mốc $70k. Tìm hiểu các yếu tố vĩ mô và xu hướng tiếp theo.",
    seoKeywords: "bitcoin, crypto, 70k, halving",
    allowComments: true,
    isFeatured: false,
    scheduledDate: "",
  },
  {
    id: "NEWS003",
    title: "Top 10 NFT Collections đáng chú ý trong tháng 5/2024",
    slug: "top-10-nft-collections-dang-chu-y-trong-thang-5-2024",
    summary: "Tháng 5 chứng kiến sự bùng nổ của nhiều bộ sưu tập NFT ấn tượng trên các hệ sinh thái Layer 2.",
    content: "Các bộ sưu tập NFT thế hệ mới đang tập trung vào khả năng ứng dụng thực tế (Utility NFT) thay vì chỉ là tác phẩm nghệ thuật kỹ thuật số đơn thuần.",
    category: "NFT",
    tags: ["NFT", "DigitalArt", "Layer2"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=nft",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PUBLISHED",
    createdDate: "23/05/2024 09:15",
    views: 1234,
    seoTitle: "Top 10 bộ sưu tập NFT đáng chú ý tháng 5/2024",
    seoDescription: "Tổng hợp các NFT tiềm năng và xu hướng thị trường NFT.",
    seoKeywords: "nft, collections, digital art",
    allowComments: false,
    isFeatured: false,
    scheduledDate: "",
  },
  {
    id: "NEWS004",
    title: "Metaverse là gì? Tương lai của Internet",
    slug: "metaverse-la-gi-tuong-lai-cua-internet",
    summary: "Metaverse không chỉ là một xu hướng nhất thời, mà có thể là tương lai của Internet thế hệ tiếp theo.",
    content: "Thế giới ảo Metaverse tích hợp VR/AR sẽ tạo ra không gian làm việc, vui chơi và giao thương hoàn toàn mới vượt giới hạn vật lý.",
    category: "Metaverse",
    tags: ["Metaverse", "VR", "AR"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=metaverse",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "DRAFT",
    createdDate: "22/05/2024 14:20",
    views: 0,
    seoTitle: "Metaverse là gì? Xu hướng công nghệ tương lai",
    seoDescription: "Tìm hiểu định nghĩa Metaverse và tiềm năng phát triển của vũ trụ ảo.",
    seoKeywords: "metaverse, vr, ar, tương lai",
    allowComments: true,
    isFeatured: false,
    scheduledDate: "",
  },
  {
    id: "NEWS005",
    title: "Smart Contract là gì? Hướng dẫn chi tiết cho người mới",
    slug: "smart-contract-la-gi-huong-dan-chi-tiet-cho-nguoi-moi",
    summary: "Smart Contract là nền tảng cốt lõi của Web3. Tìm hiểu cách hoạt động và ứng dụng thực tiễn.",
    content: "Hợp đồng thông minh tự động thực thi các điều khoản khi đáp ứng đủ điều kiện mà không cần bên thứ ba đáng tin cậy.",
    category: "Blockchain",
    tags: ["SmartContract", "Solidity", "Blockchain"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=smartcontract",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PENDING_REVIEW",
    createdDate: "21/05/2024 11:05",
    views: 0,
    seoTitle: "Smart Contract là gì? Cẩm nang Blockchain cho người mới",
    seoDescription: "Hướng dẫn dễ hiểu nhất về hợp đồng thông minh blockchain.",
    seoKeywords: "smart contract, solidity, blockchain, web3",
    allowComments: true,
    isFeatured: false,
    scheduledDate: "",
  },
  {
    id: "NEWS006",
    title: "DeFi là gì? Cơ hội và rủi ro trong DeFi",
    slug: "defi-la-gi-co-hoi-va-rui-ro-trong-defi",
    summary: "DeFi đang mở ra một kỷ nguyên tài chính phi tập trung. Cùng khám phá cơ hội kiếm lợi nhuận và rủi ro kèm theo.",
    content: "Tài chính phi tập trung DeFi cho phép vay mượn, giao dịch, và tạo lợi nhuận hoàn toàn ngang hàng thông qua các giao thức blockchain.",
    category: "DeFi",
    tags: ["DeFi", "YieldFarming", "Lending"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=defi",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PUBLISHED",
    createdDate: "20/05/2024 08:30",
    views: 3421,
    seoTitle: "DeFi là gì? Cơ hội đầu tư và rủi ro tiềm ẩn",
    seoDescription: "Tất tần tật về tài chính phi tập trung DeFi.",
    seoKeywords: "defi, yield farming, lending, crypto",
    allowComments: true,
    isFeatured: true,
    scheduledDate: "",
  },
  {
    id: "NEWS007",
    title: "Hướng quan trọng bảo mật ví Crypto an toàn 100%",
    slug: "huong-dan-bao-mat-vi-crypto-an-toan-100",
    summary: "Bảo mật ví Crypto là yếu tố quan trọng hàng đầu để bảo vệ tài sản số của bạn trước hacker.",
    content: "Hãy giữ cụm từ khôi phục (seed phrase) ngoại tuyến hoàn toàn, tuyệt đối không chụp ảnh lưu trên điện thoại và sử dụng ví lạnh khi lưu trữ lượng lớn crypto.",
    category: "Tutorial",
    tags: ["Security", "Wallet", "Crypto"],
    thumbnail: "https://api.dicebear.com/7.x/shapes/svg?seed=security",
    authorName: "Admin VIFC",
    authorAvatar: "/icons/icon_sidebar2.png",
    status: "PUBLISHED",
    createdDate: "19/05/2024 16:10",
    views: 2111,
    seoTitle: "Bảo mật ví Crypto an toàn tuyệt đối | Hướng dẫn 2024",
    seoDescription: "Các nguyên tắc sống còn để bảo vệ ví tiền điện tử của bạn.",
    seoKeywords: "bao mat vi, crypto wallet, seed phrase, vi lanh",
    allowComments: true,
    isFeatured: false,
    scheduledDate: "",
  }
];

export const CATEGORY_OPTIONS = [
  { label: "Web3", value: "Web3" },
  { label: "Crypto", value: "Crypto" },
  { label: "NFT", value: "NFT" },
  { label: "Metaverse", value: "Metaverse" },
  { label: "Blockchain", value: "Blockchain" },
  { label: "DeFi", value: "DeFi" },
  { label: "Tutorial", value: "Tutorial" }
];

export const STATUS_OPTIONS = [
  { label: "Tất cả trạng thái", value: "ALL" },
  { label: "Đã xuất bản", value: "PUBLISHED" },
  { label: "Bản nháp", value: "DRAFT" },
  { label: "Chờ duyệt", value: "PENDING_REVIEW" },
  { label: "Đã lưu trữ", value: "ARCHIVED" }
];
